
apiVersion: 1

datasources:
  - name: se4as-influxdb
    type: influxdb
    url: ${INFLUX_URL}
    uid: ${INFLUXDB_DATASOURCE_UID}
    access: proxy
    isDefault: true
    jsonData:
      version: Flux
      organization: ${DOCKER_INFLUXDB_INIT_ORG}
      defaultBucket: ${DOCKER_INFLUXDB_INIT_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
  - name: seas-mongodb
    type: mongodb
    url: ${MONGO_URL}
    database: ${MONGO_DB}
